env:
 global:
  - secure: some_value
  - secure: some_other_value

stages:
 - test
 - name: build_staging
   if: branch = development AND type = push
 - name: build_release
   if: branch = master AND type = push

jobs:
 include:
   - stage: test
     name: "xUnit Tests"
     language: csharp
     solution: placeholder.sln
     mono: none
     dotnet: 2.1
     script:
       - dotnet restore
   - stage: build_staging
     name: "Build docker staging image"
     sudo: required
     services:
       - docker
     script:
       - ./bin/docker.sh staging
   - stage: build_release
     name: "Build docker release image"
     sudo: required
     services:
       - docker
     script:
       - ./bin/docker.sh latest